---
# .gitlab-ci.yml **parent**
stages:
  - test
  - build
  - trigger

variables:
    PARENT_PROJECT: $CI_PROJECT_NAME

test:
  script:
    - echo "Exécution des tests - OK"

build:
  stage: build
  script:
    - echo "Build action"
    - echo "COMMIT_MESSAGE=${CI_COMMIT_MESSAGE}" > build.env
  artifacts:
    reports:
      dotenv: build.env

trigger:
  stage: trigger
  variables:
    PARENT_COMMIT_MESSAGE: $COMMIT_MESSAGE
  trigger:
    strategy: depend
    project: <chemin_groupe>/<projet_enfant>

---
# .gitlab-ci.yml **enfant**
stages:
  - .pre
  - test
  - trigger

job:
  script:
    - echo "Hello world"

triggered:
  stage: trigger
  script:
    - echo "Exécution via un projet en amont"
    - echo "Build du projet - ${PARENT_PROJECT}"
    - echo "Message du projet - ${PARENT_COMMIT_MESSAGE}"
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"